runtime: python311  # Använd den Python-version som stöds och som du utvecklar för.
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /(.*\.(html))
  static_files: \1
  upload: (.*\.(html))
  secure: always
  redirect_http_response_code: 301

env_variables:
  MAIL_SERVER: 'smtp.gmail.com'
  MAIL_PORT: '587'
  MAIL_USE_TLS: 'True'
  MAIL_USERNAME: 'din_gmail_användare'
  MAIL_PASSWORD: 'ditt_gmail_lösenord'